export const mapClassToLabel: Record<string, string> = {
  anemona: 'Anemona',
  barba_de_viejo: 'Barba de Viejo',
  cachiyuyo: 'Cachiyuyo',
  cadillo: 'Cadillo',
  calafate: 'Calafate',
  canelo: 'Canelo',
  chaura: 'Chaura',
  flor_de_papel: 'Flor de papel',
  frutilla_del_diablo: 'Frutilla del diablo',
  frutilla_silvestre: 'Frutilla silvestre',
  guindo: 'Guindo',
  lenadura: 'Leña dura',
  lenga: 'Lenga',
  maiten_enano: 'Maitén enano',
  matanegra: 'Matanegra',
  michay: 'Michay',
  murtilla: 'Murtilla',
  nire: 'Ñire',
  notro: 'Notro',
  orquidea_amarilla: 'Orquídea amarilla',
  palomita: 'Palomita',
  parrilla: 'Parilla',
  perezia_azul: 'Perezia azul',
  punque: 'Punque',
  violeta_amarilla: 'Violeta amarilla',
};
